CREATE SEQUENCE DOC_ID_SEQ;

CREATE TABLE DOCUMENT (
  ID            INT           PRIMARY KEY AUTO_INCREMENT,
  NAME          VARCHAR2(32)   NOT NULL,
  UPDATE_DATE   TIMESTAMP     NOT NULL,
  CONTENT_TYPE  VARCHAR2(32)   NOT NULL
);
